### PR TITLE
Pull to proper branch

### PR DESCRIPTION
**Pull request by TamedFlame**
## Changes / Comments

Modified the sheet mainly in the CSS file, to improve it's readability. Tables, rows, and inputs now have background colors to facilitate visual navigation and identification of elements. Improved the vertical alignment of inputs and other elements within the table rows, to further ease the user's eyes path across them. 

The sheet has been modified to use CSS variables, so that, if need be, the color scheme may be easily modified by altering a few variables on the beginning of the sheet. Using this feature, I've added an array of "Sheet Styles", preset combinations of colors that can be selected via a setting in the appropiate tab of the sheet.

## Added Styles:

 - Green
- Blue
- Beige
- Gray
- Classic White

    
## Added variables:
   
-  main-text: Controls main text color.
-  highlight-text: Controls highlighted, formerly _darkred_, text color.
-  secondary-highlight: Controls the secondary highlighted text color used mainly in the Attribute table.
- point-label-text: Controls the text color for the points label with a hover info box.
-  header-text: Controls the text color for headings.
-  sheet-bg: Controls base background color for the sheet.
-  box-bg: Controls background color for tables.
-  header-bg: Controls background color for table and other headings.
-  row-bg: Controls background color for even table rows.
-  odd-row-bg: Controls background color for odd table rows.
-  input-disabled-bg: Controls background color for the disabled inputs.
-  border-color: Controls main border color.

Not all instances of color within the sheet have been retrofited into this system, to avoid generating too many variables for specific elements.

### CODE REVIEW

**Comment by MadCoder253** [comment]
Excellent, thank you @TamedFlame

**Comment by MadCoder253** [comment]
I'm going to shoot for getting this update for this Tuesday's pull into roll20. I have to work today, so I'm going to check it out tonight.

**Comment by MadCoder253** [comment]
Hi @TamedFlame I found a few display bugs, but I don't have time to identify all of them, but here are a few of them. 

- On the Traits tab, the show/hide arrow buttons are missing.
- On the Bio/Misc tab, the text areas for **Background History & Notes**, **Training** boxes are too short.
- Skills tab. Both technique tables, the show/hide button and checboxes are missing
- Combat tab.  Active defenses. The show/hide button and checkboxes are off. Need to click the exact spot to work. 
- Combat tab. Combat Tools - Thrown box. Show/hide button is missing
- Options tab. Looks like the rows and columns for the options are not lining up correctly. The horizontal rulers are also out of place.

**Comment by TamedFlame** [comment]
@MadCoder253 modified my code so that all the changes you noted were fixed. Additionally, made it so the new styles will color the options page, so the user gets instant feedback for the changes. (Classic White remains as before). Also improved my bordered expands, so when doing so from ones with no highlight checkbox, their border is properly aligned to the input's left border.

I could not replicate your issue with Active Defenses, on my browser the toggle and checkbox are both switched, and they respond to being clicked on, with no misalignment.

**Comment by MadCoder253** [comment]
Thanks for all the hard work @TamedFlame looks great. I just merged into my branch and it should go live on Tuesday.

**Comment by TamedFlame** [comment]
Ken, I am working to fix up the design complaints on the forum, as well as doing a few touchups and adding new styles.

Do you have an instant messaging service you'd be comfortable using for the sake of easier communication?

**Comment by MadCoder253** [comment]
Sounds good, here's the current branch that I will be doing a pull request for the 5/5/2020 updates.

https://github.com/MadCoder253/roll20-character-sheets/tree/GURPS-2.3.4

Mike W and I use discord. My account is TheMadCoder#4254

Ken

**Comment by MadCoder253** [comment]
@TamedFlame I found an issue, are you able to fix this?

https://github.com/MadCoder253/roll20-character-sheets/issues/157

**Pull request merged**
