### PR TITLE
Sheet Styles functionality for GURPS

### PR DESCRIPTION
**Pull request by TamedFlame**
## Changes / Comments

Modified the sheet mainly in the CSS file, to improve it's readability. Tables, rows, and inputs now have background colors to facilitate visual navigation and identification of elements. Improved the vertical alignment of inputs and other elements within the table rows, to further ease the user's eyes path across them. 

The sheet has been modified to use CSS variables, so that, if need be, the color scheme may be easily modified by altering a few variables on the beginning of the sheet. Using this feature, I've added an array of "Sheet Styles", preset combinations of colors that can be selected via a setting in the appropiate tab of the sheet.

## Added Styles:

 - Green
- Blue
- Beige
- Gray
- Classic White

    
## Added variables:
   
-  main-text: Controls main text color.
-  highlight-text: Controls highlighted, formerly _darkred_, text color.
-  secondary-highlight: Controls the secondary highlighted text color used mainly in the Attribute table.
- point-label-text: Controls the text color for the points label with a hover info box.
-  header-text: Controls the text color for headings.
-  sheet-bg: Controls base background color for the sheet.
-  box-bg: Controls background color for tables.
-  header-bg: Controls background color for table and other headings.
-  row-bg: Controls background color for even table rows.
-  odd-row-bg: Controls background color for odd table rows.
-  input-disabled-bg: Controls background color for the disabled inputs.
-  border-color: Controls main border color.

Not all instances of color within the sheet have been retrofited into this system, to avoid generating too many variables for specific elements.

### CODE REVIEW

**Comment by MadCoder253** [comment]
Thanks @TamedFlame! I won't have time to look at this until tomorrow.

**Comment by TamedFlame** [comment]
You might need to wait, sadly my changes and the ones made since the march 24 update didn't merge properly.

**Comment by TamedFlame** [comment]
It should be ready now, had to remake my changes over your fork's HTML and CSS.

**Comment by TamedFlame** [comment]
@MadCoder253 Sneaked in a minor correction that had reverted when migrating my changes. Did you have a chance to look into them? 

Keep in mind, I made a change to the expandable tabs on skills, combat and items. (Gave them a left margin and edge so they'd properly separate visually from their box, and to align their contents with the expand toggle.) Tell me if it works for you!

**Comment by MadCoder253** [comment]
Hi @TamedFlame thanks for all the hard work and smart updates, especially the option to select a theme. I'm also going to tag @KlingonMike. Please don't be overwhelmed by this long comment, most of them are basically the same revision for each tab of the character sheet and describing some misalignments.

## Revisions

> Keep in mind, I made a change to the expandable tabs on skills, combat and items. (Gave them a left margin and edge so they'd properly separate visually from their box, and to align their contents with the expand toggle.) Tell me if it works for you!

The border is good, but the left margin is taking up space that we might need in the future, please remove the left margin. The left margin also caused the content to overflow causing the text areas to be too wide.

- Please remove your lines with console.log()
- Please return roll template styles back to their original styles. 
- General Tab.
  - The spacing between the **STATS VALUE MOD PTS** and **NOTES** boxes is missing. (Let me know if you need a screenshot.)
  - The areas for **STATS VALUE MOD PTS** and **LIFTING & MOVING WEIGHT** should have the same width. (Let me know if you need a screenshot.)
  - **POINT SUM** column has css selectors that shows the correct fields based on what the user chose on the Options tab called **Point Summary Layout**. Each option displays the point summary based on a character sheet system; GCA, GCS, and all. You can look at the current sheet to see how it works. **NOTE** There are several fields that show/hide based on the format because each format uses a different formula to calculate totals.
- Traits Tab
  - Advantages, Perks, Quirks, Disadvantages, and Racial Traits tables. For each table the expanded area is shifted to the right causing the content to overflow. Please flush the expanded area to the left and fit the content into the area.
- Skills Tab
  - Skills, Techniques (legacy), and Techniques (Revised) tables. For each table the expanded area is shifted to the right causing the content to overflow. Please flush the expanded area to the left and fit the content into the area.
- Combat Tab
  - Active Defenses area and tables. The expanded area is shifted to the right causing the content to overflow. Please flush the expanded area to the left and fit the content into the area.
  - Apply Combat Reflexes checkbox. The checkbox is bleeding into the **Defense Bonus (DB) Notes** heading. Can you resize the checkbox or increase the line height?
  - Melee Attacks and Ranged Attacks tables. For each table, the expanded areas have the original style and are not using the new bordered style. Can you update the expanded areas so they all have the same format?
  - For the tool labeled **Range Calculator for Ranged Attacks only** the column headings appear to be on the same line as the title. Please move them below the tool title and ensure the column headings line up with the fields. (Let me know if you need a screenshot, you can also look at the current character sheet)
  - For the **Falling and Collision** table, the column headings should be on the next line and line up with the fields.  (Let me know if you need a screenshot, you can also look at the current character sheet)
  - For the **Demolition** tool, the column headings should be on the next line and line up with the fields.  (Let me know if you need a screenshot, you can also look at the current character sheet)
- Inventory Tab. 
  -Inventory table. The expanded area is shifted to the right causing the content to overflow. Please flush the expanded area to the left and fit the content into the area.
- Grimoire Tab.
  - Spells table. The expanded area is shifted to the right causing the content to overflow. Please flush the expanded area to the left and fit the content into the area.
- Gear Icon Tab (Options)
  - Can you move "Selects a visual style for the character sheet" above the drop-down? The default version should be Classic White, please move that to the top and have it selected.

## Classic White Revisions

- Combat Tab.
  - Active Defenses table. On the column header area, the row starts with a section of white. Please have that box have the same background color as the rest of the row.  (Let me know if you need a screenshot) 
  - Hit Location box. Keep the background color for **Hit Location** but change the background color for **WHERE PEN DR** row to white.
- Grimoire Tab. 
  - For row that contains **SPELLS BASED ON:** change the background color to white.
  
## Optional Fixes

- General Tab.
  - With the column headers having a background color there's an obvious misalignment of the text. You will notice how the text for **ATTRIBUTES MOD PTS**, **STATS VALUE MOD PTS**, **NOTE**, and **POINT SUM** are not aligned vertically. The section **STATS VALUE MOD PTS** is too low, while **POINT SUM** is too high. Can you fix this?
- Expand Button. It might be a good idea to move the expand button to the far left, but I want to check with Mike. We're also thinking of moving the dice location, but that can wait.

**Comment by TamedFlame** [comment]
@MadCoder253 With this last commit, I should've covered all your comments, including the reordering of the expand and highlight buttons (the implementation of this feature is not the most sensible, but I managed) and alignment issues. I also corrected the Classic White theme to more accurately match the current design.

I have not changed yet the left margin for the expanded fields, but I corrected the overflow error. On all color schemes but Classic White, having the expand be as wide as the container is visually unseemly, as it breaks both the background color, and the continuity of it's header, as the content becomes wider.

I've ensured none of the current expands break under the 58 pixel thinner size, could it be possible to keep it that way?

**Comment by MadCoder253** [comment]
Thanks @TamedFlame!

> I've ensured none of the current expands break under the 58 pixel thinner size, could it be possible to keep it that way?

We'll keep it that way for now. I'll check out the code, I've been working extremely late from Wednesday to Friday and I had to catch up with sleep today. 

I do have one more favor to ask. Could change the pull request from MadCoder253:master to MadCoder253:gurps-2.3.3? Roll20.net's requirement for pull requests is to use a new branch into their master branch.

**Comment by TamedFlame** [comment]
@MadCoder253 [Here](https://github.com/MadCoder253/roll20-character-sheets/pull/145)'s the new PR

**Pull request closed without merging**
